spring:
  application:
    name: marketuser

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: tjdb79ERpbO7fZ0lmU7N
            client-secret: LzBHj360fR
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - mobile
            authorization-grant-type: authorization_code
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token

            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


server:
  port: 8080

logging:
  level:
    com.project.marketplace: DEBUG
    org.mybatis: DEBUG
    org.springframework.security: DEBUG

# JWT 설정 추가
jwt:
  secret: bXlTdXBlclNlY3JldEtleUZvcklzc3VpbmdKV1RUb2tlbnNJbk1hcmtldHBsYWNlQXBwbGljYXRpb24=
  expiration: 86400000  # 24시간(밀리초)